### ISSUE TITLE
should it be a empty repo here

### ISSUE THREAD

**Issue by fuzheng1998** [fencer-so/CommBank-Server#1]
I am following the instruction on theforage.com, but why this repo is empty? is it ready now?

![Screen Shot 2022-10-25 at 21 35 12](https://user-images.githubusercontent.com/24203166/197751703-83f9b0b6-0759-4cd6-aece-2d7b9522a86f.png)

**Comment by AllenSHH** [comment]
I also confused about this.

**Comment by Tedzzzz** [comment]
+1

**Comment by Prestonccc** [comment]
+1

**Comment by fuzheng1998** [comment]
hey guys, if you are feeling same, you can give a 👍 to me. **Please, please don't use +1+1 again and againto make this issue longer and longer!** 

Just imagine if hundreds of people reply +1, it is very hard for others finding latest reply at the bottom. 

+1 is not good practice on GitHub.

**Comment by Arif-arsh** [comment]
👍

**Comment by matt-ramotar** [comment]
Thanks for your patience. Migrated starter code this morning. Closing this issue out but happy to help if anything further comes up

**Comment by YoosufIsmail-dev** [comment]
git add .
git commit -m "Add support for goal icons

- Add optional Icon field to Goal model (backend)
- Update TypeScript Goal model and display icon on goal card
- Integrate emoji-mart picker in GoalManager
- Add PUT request to persist icon changes, wire up pickEmojiOnClick
- Add xUnit tests covering GetGoalsForUser with icon field"

**Comment by YoosufIsmail-dev** [comment]
git push -u origin feature/goal-icons

**Comment by YoosufIsmail-dev** [comment]
## Summary
Adds support for custom icons on Goals, end-to-end (backend, frontend, and tests).

## Changes
- **Backend (rSERVER)**: Added optional `Icon` field (string) to the `Goal` model, ignored if null for backward compatibility with existing seeded documents.
- **Frontend (rWEB)**: Updated the TypeScript `Goal` model with an optional `icon` field, displayed the icon on the goal card, and integrated emoji-mart (v3.0.1) as the icon picker in `GoalManager`.
- **Integration**: Added a `PUT` request to persist icon changes to the backend, and finished the `pickEmojiOnClick` handler so selecting an emoji saves immediately and survives a client refresh.
- **Tests**: Added xUnit coverage for the `GetGoalsForUser` route, including cases for goals with and without an icon set.

## Testing
- Verified via Postman that goal responses include the `icon` field after the model change.
- Verified icon changes persist after a client refresh.
- All new xUnit tests pass locally.
